apiVersion: v1
kind: Pod
metadata:
  name: init-container
  labels:
     app: initContainerPod
     version: 1.0.0
spec:
  initContainers:
  - name: init-myservice
    image: busybox:1.29
    command: ["sh", "-c", "until nslookup myservice; do waiting for myservice; sleep 5; done"]

  containers:
  - name: my-app-container
    image: busybox:1.29
    command: ["sh","-c", "echo The service is running && sleep 3600"]