apiVersion: v1
kind: Pod
metadata:
    name: ambassador-pod
    labels:
      version: 1.0.0
      app: ambassador-app
spec:
  volumes:  
  - name: shared
    emptyDir: {}
    
  containers:
  - name: app-container-poller
    image: yauritux/busybox-curl
    command: ["/bin/bash"]
    args: ["-c", "while true; do curl 127.0.0.1:81 > /usr/share/nginx/html/index.html; sleep 10; done"]
    volumeMounts:
    - name: shared
      mountPath: /usr/share/nginx/html
  - name: app-container-server
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
    - name: shared
      mountPath: /usr/share/nginx/html
  - name: ambassador-container
    image: bharmicrosystems/nginx-forward-proxy
    ports:
      - containerPort: 81
       