kind: Deployment
apiVersion: apps/v1
metadata:
  name: resource-analyst
spec:
  replicas: 10
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
    spec: 
      containers:
      - name: redis
        image: redis:6.2
        resources:
          requests:
            memory: 200Mi
            cpu: 100m 
          limits:
            memory: 400Mi
            cpu: 1
