apiVersion: v1
kind: Pod
metadata:
  name: test-pod3
spec:
  containers:
  - name: testpod3
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh','-c','echo Pod3 is running; sleep 5000;']
    resources:
      requests:
        cpu: "10m"
      limits:
        cpu: '200m'
  restartPolicy: Never