apiVersion: v1
kind: Service
metadata:
  name: fnt-service
  labels:
    app: nginx-1.1
    env: prod

spec:
  type: LoadBalancer
  selector:
    app: nginx-1.1
    
  ports:
    - port: 80
      targetPort: 80