apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-persistant-vol

spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Recycle

  capacity: 
    storage: 1Gi

  accessModes:
    - ReadWriteOnce

  hostPath:
    path: /var/tmp
