apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-test
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 5
      template:
        spec:
          containers:
            - name: cron-test
              image: busybox:1.36.1
              args: 
                - /bin/sh
                - -c
                - "date; echo hello this is a cron test"
          restartPolicy: OnFailure
